version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASS}
      GF_SERVER_ROOT_URL: "http://43.204.216.68/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

  gdrive:
    build: ./MiniGDrive
    container_name: gdrive
    ports:
      - "127.0.0.1:6000:6000"
    volumes:
      - /home/ubuntu/minigdrive_data/uploads:/app/uploads
      - /home/ubuntu/minigdrive_data/trash:/app/trash
      - /home/ubuntu/minigdrive_data/storage:/app/storage
      - /home/ubuntu/minigdrive_data/users.db:/app/users.db
      - /home/ubuntu/minigdrive_data/profiles:/app/static/profiles
    environment:
      SECRET_KEY: ${SECRET_KEY}
    restart: unless-stopped

volumes:
  grafana_data:
