global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "gdrive"
    static_configs:
      - targets: ["gdrive:6000"]
 