name: EC2
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print hello
        run: echo "Hello world"
      - name: print name
        run: echo "My name is ${{ github.actor }}"