name: test and deploy to ec2
on:
  push:
    branches:
      main

jobs:
  testanddeploy:
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          sudo apt install pytest
          pytest
             
