name: CI/CD - Docker + Nginx + PostgreSQL

on:
  push:
    branches:
      - extras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and Install Docker + Nginx
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.INSTANCE_IP2 }} << 'EOF'
          set -e
          echo "[+] Updating packages..."
          sudo apt-get update -y

          echo "[+] Installing Docker if not installed..."
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io
            sudo usermod -aG docker ubuntu
          fi

          echo "[+] Installing Nginx if not installed..."
          if ! command -v nginx &> /dev/null; then
            sudo apt-get install -y nginx
          fi
        EOF

    - name: Upload nginx config
      run: |
        scp -o StrictHostKeyChecking=no nginx/minigdrive.conf ubuntu@${{ secrets.INSTANCE_IP2 }}:/tmp/minigdrive.conf

    - name: SSH into EC2 and Deploy App
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.INSTANCE_IP2 }} << 'EOF'
          set -e

          echo "[+] Moving nginx config into place..."
          sudo mv /tmp/minigdrive.conf /etc/nginx/sites-available/minigdrive
          sudo ln -sf /etc/nginx/sites-available/minigdrive /etc/nginx/sites-enabled/minigdrive
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t && sudo fuser -k 80/tcp || true
          sudo systemctl restart nginx

          echo "[+] Cloning or pulling latest code..."
          if [ ! -d "MiniGDrive" ]; then
            git clone https://github.com/Aswin-AR5055/MiniGDrive.git MiniGDrive
          fi

          cd MiniGDrive

          echo "[+] Pulling latest changes..."
          git fetch --all
          git reset --hard origin/extras

          echo "[+] Stopping and removing existing containers..."
          docker stop gdrive || true
          docker rm gdrive || true
          docker stop minigdrive_postgres || true
          docker rm minigdrive_postgres || true

          echo "[+] Creating persistent data directories..."
          mkdir -p /home/ubuntu/minigdrive_data/uploads
          mkdir -p /home/ubuntu/minigdrive_data/trash
          mkdir -p /home/ubuntu/minigdrive_data/storage
          mkdir -p /home/ubuntu/minigdrive_data/profiles
          mkdir -p /home/ubuntu/minigdrive_data/postgres
          sudo chown -R ubuntu:ubuntu /home/ubuntu/minigdrive_data

          echo "[+] Starting PostgreSQL container..."
          docker run -d --name minigdrive_postgres \
            -e POSTGRES_DB=${{ secrets.DB_NAME }} \
            -e POSTGRES_USER=${{ secrets.DB_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -p 5432:5432 \
            -v /home/ubuntu/minigdrive_data/postgres:/var/lib/postgresql/data \
            postgres:15

          echo "[+] Building Docker image for app..."
          docker build --pull -t gdrive .

          echo "[+] Running app container with Gunicorn on localhost:6000..."
          docker run -d --name gdrive \
            -p 6000:6000 \
            -v /home/ubuntu/minigdrive_data/uploads:/app/uploads \
            -v /home/ubuntu/minigdrive_data/trash:/app/trash \
            -v /home/ubuntu/minigdrive_data/storage:/app/storage \
            -v /home/ubuntu/minigdrive_data/profiles:/app/static/profiles \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@minigdrive_postgres:5432/${{ secrets.DB_NAME }} \
            --link minigdrive_postgres:db \
            gdrive

            
          echo "[+] Waiting for PostgreSQL to be ready..."
          sleep 10

          echo "[+] Initializing database tables..."
          docker exec gdrive python db_schema.py

          echo "[+] Done. Current running containers:"
          docker ps
        EOF
