name: CI/CD - Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: SSH into EC2 and Deploy with Docker
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.INSTANCE_IP }} << 'EOF'
          set -e
          cd MiniGDrive

          echo "[+] Pulling latest changes..."
          git pull

          echo "[+] Stopping and removing existing container..."
          docker stop gdrive || true
          docker rm gdrive || true

          echo "[+] Removing existing Docker image..."
          docker rmi -f gdrive || true

          echo "[+] Creating persistent data directories..."
          mkdir -p /home/ubuntu/minigdrive_data/uploads
          mkdir -p /home/ubuntu/minigdrive_data/trash
          mkdir -p /home/ubuntu/minigdrive_data/storage
          mkdir -p /home/ubuntu/minigdrive_data/profiles
          touch /home/ubuntu/minigdrive_data/users.db
          chown -R ubuntu:ubuntu /home/ubuntu/minigdrive_data

          echo "[+] Building Docker image..."
          docker build -t gdrive .

          echo "[+] Running container with volume mounts and secret key..."
          docker run -d --name gdrive \
            -p 80:5000 \
            -v /home/ubuntu/minigdrive_data/uploads:/app/uploads \
            -v /home/ubuntu/minigdrive_data/trash:/app/trash \
            -v /home/ubuntu/minigdrive_data/storage:/app/storage \
            -v /home/ubuntu/minigdrive_data/users.db:/app/users.db \
            -v /home/ubuntu/minigdrive_data/profiles:/app/static/profiles \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            gdrive

          echo "[+] Done. Current running containers:"
          docker ps
        EOF