name: Test and Deploy to EC2 with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH into EC2 and Deploy with Docker
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@43.204.216.68 << 'EOF'
          set -e
          cd MiniGDrive

          echo "[+] Pulling latest changes..."
          git pull

          echo "[+] Stopping and removing existing container..."
          sudo docker stop gdrive || true
          sudo docker rm gdrive || true

          echo "[+] Creating persistent data directories..."
          mkdir -p /home/ubuntu/minigdrive_data/uploads
          mkdir -p /home/ubuntu/minigdrive_data/trash
          mkdir -p /home/ubuntu/minigdrive_data/storage
          touch /home/ubuntu/minigdrive_data/users.db
          sudo chown -R ubuntu:ubuntu /home/ubuntu/minigdrive_data

          echo "[+] Building Docker image..."
          sudo docker build -t gdrive .

          echo "[+] Running container with selective volume mounts and secret key..."
          sudo docker run -d --name gdrive \
            -p 80:5000 \
            -v /home/ubuntu/minigdrive_data/uploads:/app/uploads \
            -v /home/ubuntu/minigdrive_data/trash:/app/trash \
            -v /home/ubuntu/minigdrive_data/storage:/app/storage \
            -v /home/ubuntu/minigdrive_data/users.db:/app/users.db \
            -e SECRET_KEY='d7b9664071b3c43bda23bae9b90f115b1dbe92883352a58f4bfa211ca80835f1' \
            gdrive

          echo "[+] Deployment complete. Container status:"
          sudo docker ps
        EOF
